const LabelConfig={
    name: "Name",
    contact: "Contact Number",
    altcontact: "Alternate Contact Number",
    email: "Email Address",
    address: "Address",
    city:"City",
    state:"State",
    dob: "Date Of Birth",
    gender: "Gender",
    maritalStatus: "Marital Status",
    religion: "Religion",
    salary: "Total Yearly Income",
    occupation: "Occupation",
    aadhar: "Aadhar Number",
    aadharimg: "Aadhar Card Image",
    bioChildren: "Number of Children",
    website: "Website/Social Media Link",
    name_contact:"Name of Contact Person",
    desg_contact:"Designation of Contact Person",
    year: "Year of Establishment",
    num_child:"Number of Children Under Care",
    healthStatus: "Health Status",
    medicalCertificates: "Medical Certificate",
    status:"Status of form",
    regnum:"Ngo Registration Number",
    caranum:"Ngo CARA Number",
    about:"Brief Description of Ngo",
    reg_certimg:"Image of Registration Certificate",
    cara_certimg:"Image of CARA Certificate",
    logoimg:"Profile Display Picture",
    galimg1:"Gallery Image 1",
    galimg2:"Gallery Image 2",
    galimg3:"Gallery Image 3",
    testimonial1: "Testimonial 1",
    testimonial2: "Testimonial 2",
    testimonial3: "Testimonial 3",
    pass:"Password"
}
export default LabelConfig;